language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build

deploy:
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  provider: pages
  skip_cleanup: true
  target-branch: master
  on:
    branch: develop
